Algoritmo "ConversaoTemperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 12/09/2022
Var
c, f, conversao:real


Inicio
escreva("Digite a temperatura em Celsius: ")
leia(c)

conversao <- (c * 9/5) + 32

escreva(c, "°C é igual a: ",conversao,"°F")



Fimalgoritmo