Algoritmo "MediaAluno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 12/09/2022
Var
n1, n2, n3, media: real


Inicio
escreva("Digite a 1° nota: ")
leia(n1)
escreva("Digite a 2° nota: ")
leia(n2)
escreva("Digite a 3° nota: ")
leia(n3)

media <- ((n1 * 2)  + (n2 * 3) + (n3 * 5)) / 10

escreval("A média do aluno foi: ", media)

Fimalgoritmo