Algoritmo "PositivoNegativo-EX15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 12/09/2022
Var
numero:inteiro


Inicio
escreva("Digite um número: ")
leia(numero)

se numero mod 2 = 0 entao
   escreval(numero, " é par!")
senao
   escreval(numero, " é impar!")
fimse


Fimalgoritmo