Algoritmo "VerificaSeEMaioQ10-EX14"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2022
Var
num: inteiro


Inicio
escreva("Digite um número: ")
leia(num)

se num > 10 entao
   escreval("É maior que 10!")
senao
   escreval("É menor que 10!")
fimse

Fimalgoritmo