Algoritmo "VerificaQualEMaior-EX19"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 12/09/2022
Var
num1, num2:inteiro


Inicio
escreval("Digite um valor: ")
leia(num1)
escreval("Digite outro valor: ")
leia(num2)

se num1 > num2 entao
   escreval("O maior valor é: ", num1)
senao
   escreval("O maior valor é: ", num2)
fimse



Fimalgoritmo