Algoritmo "LataDeOleo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2022
Var
altura, raio, volume: real


Inicio
escreva("Digite a altura da lata: ")
leia(altura)
escreva("Digite o raio da lata: ")
leia(raio)

volume <- pi * (raio ^ 2) * altura

escreva("O volume da lata é de: ",volume:2:2,"m³")


Fimalgoritmo