Algoritmo "NumeroSucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 09/09/2022
Var
numero, sucessor: inteiro


Inicio
escreva("Digite um número: ")
leia(numero)

sucessor <- numero - 1

escreva("O número sucessor é: ", sucessor)


Fimalgoritmo