Algoritmo "NumeroAntecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Oliveira Mendes
// Data atual  : 09/09/2022
Var
numero, antecessor: inteiro


Inicio
escreva("Digite um número: ")
leia(numero)

antecessor <- numero - 1

escreva("O número antecessor é: ", antecessor)


Fimalgoritmo